name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

commands:
    test:
        description: A simple test command
        permission: gods.test
        usage: /gods test

permissions: {}