name: ${name}
version: 1.20.1
description: ${description}
author: ${author}
website: ${url}
api-version: '1.20'

main: ${mainClass}

commands:
    test:
        description: A simple test command
        permission: gods.test
        usage: /gods test

permissions: {}